### ISSUE TITLE
Referencement

### ISSUE THREAD

**Issue by MeznedMarwa** [reworkcss/rework-plugin-references#1]
Hi everybody,
I try to minimize my speed page but i can't
Message Error Is " Éliminer les codes JavaScript et CSS qui bloquent l'affichage du contenu au-dessus de la ligne de flottaison "
What can I do?
Please help me

**Comment by conradz** [comment]
I'm pretty sure this is not related to this plugin. It sounds like you are using PageSpeed and getting messages from that. You may want to take a look at [this page](https://developers.google.com/speed/docs/insights/BlockingJS) to see how to fix this warning. For questions about PageSpeed, refer to [its documentation](https://developers.google.com/speed/).
